global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtpServer'
  smtp_from: 'senderEmail'
  smtp_auth_username: 'senderUsername'
  smtp_auth_password: 'senderLoginPassword'
  smtp_require_tls: false
route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 5m
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'receiverEmail'
    send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
