version: '2'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
# Prometheus
  prometheus:
    image: "prom/prometheus"
    hostname: prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    depends_on:
      - cadvisor
    restart: always

# cAdvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.36.0
    hostname: cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8080:8080'
    restart: always

# Grafana 
  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: always

# alertmanager
  alermanager:
    image: prom/alertmanager
    ports:
      - '9093:9093'
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    restart: always
