version: '3'
services:
  openemr-docker-alpine:
    restart: always
    build: openemr/
    ports:
    - 80:80
    volumes:
    - logvolume01:/var/log
    - sitevolume:/var/www/localhost/htdocs/openemr/sites/default
    links:
    - mysql
  mysql:
    restart: always
    command: ['mysqld', '--character-set-server=utf8']
    image: percona/percona-server:5.6
    volumes:
    - sqlbackup:/mnt/backups    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openemr
volumes:
  sqlbackup: {}
  logvolume01: {}
  sitevolume: {}
