#!/bin/bash
# Function: Install the base services, e.g. git docker docker-compose and openemr-cmd
# The script support Mac OS 10.13 or later.
CODE_LOCATION=$1
GITHUB_ACCOUNT=$2

git_clone_function(){
    CODE_LOCATION=$1
    GITHUB_ACCOUNT=$2
    cd ${CODE_LOCATION} && [ `pwd` != "${CODE_LOCATION}" ] && cd ${CODE_LOCATION}
    echo -e "\033[30m===>\033[0m \033[32mDownloading OpenEMR repository... \033[0m"
    echo ''
    git clone https://github.com/${GITHUB_ACCOUNT}/openemr.git
    cd ${CODE_LOCATION}/openemr && [ `pwd` != "${CODE_LOCATION}/openemr" ] && cd ${CODE_LOCATION}/openemr
    git remote add upstream https://github.com/openemr/openemr.git
    git fetch upstream
    echo ''
    echo -e "\033[30m===>\033[0m \033[32mPulling the latest data... \033[0m"
    echo ''
    git pull upstream master
    echo ''
}

# Script Usage
EXIT_CODE=11
if [ $# -ne 2 ]
then
    echo "Usage: bash `basename $0` <code location> <github account>"
	echo ''
    echo "  e.g. bash `basename $0` /Users/test/code testuser"
	echo ''
	echo -e "\033[33mNOTE-1: Please try to set the full path for code location.\033[0m"
    echo -e "\033[33mNOTE-2: Please make sure you have created your own fork of OpenEMR at first.\033[0m"
    exit $EXIT_CODE
fi

# Install brew
# Homebrew info: https://brew.sh
which brew &>/dev/null
if [ $? -ne 0 ]
then
	echo -e "\033[30m===>\033[0m \033[32mInstalling Homebrew... \033[0m"
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
	echo ''
else
	echo -e "\033[30m===>\033[0m \033[32mHomebrew is already installed. \033[0m"
	echo ''
fi

# Install git
INSTALL_FAIL_CODE=15
which git &>/dev/null
if [ $? -ne 0 ]
then
	echo -e "\033[30m===>\033[0m \033[32mInstalling git... \033[0m"
    brew install git
    [ $? -ne 0 ] && echo '' && echo -e "\e[31mInstalled failed, please check the network.\e[0m" && exit $INSTALL_FAIL_CODE
	echo ''
else
	echo -e "\033[30m===>\033[0m \033[32mGit is already installed. \033[0m"
	echo -e "\033[33mIf your git is installed by default, and you want to upgrade it, please try:\033[0m"
	echo -e "\033[32m  brew install git\033[0m"
	echo -e "\033[32m  echo 'export PATH=/usr/local/bin:\$PATH' >> ~/.bash_profile\033[0m"
	echo -e "\033[32m  source ~/.bash_profile\033[0m"
	echo ''
fi

# Clone code to local
if [ ! -d ${CODE_LOCATION} ]
then
    mkdir -p ${CODE_LOCATION}
    git_clone_function $1 $2
elif [ ! -d ${CODE_LOCATION}/openemr ]
then
    git_clone_function $1 $2
else
    echo -e "\033[30m===>\033[0m \033[32mOpenEMR repo is already downloaded. \033[0m"
    echo ''
fi

# Install docker
which docker &>/dev/null
if [ $? -ne 0 ]
then
	echo -e "\033[30m===>\033[0m \033[32mInstalling docker... \033[0m"
	echo ''
	brew cask install docker
	echo ''
	open /Applications/Docker.app
	echo -e "\033[30m===>\033[0m \033[33mPlease click open for docker prompt window. \033[0m"
	echo -e "\033[30m===>\033[0m \033[33mPlease click ok and provide your login password for docker privileged access prompt window. \033[0m"
    while true
    do
        read -p "Please enter [yes|y] to continue if you already permitted the docker access: " CONFIRM_PERMIT
        if [ "$CONFIRM_PERMIT" == "yes" ] || [ "$CONFIRM_PERMIT" == "y" ]
        then
            break
        fi
    done
	echo ''
else
	echo -e "\033[30m===>\033[0m \033[32mDocker is already installed. \033[0m"
	echo ''
fi

# Install docker-compose
echo -e "\033[30m===>\033[0m \033[32mDocker Compose is installed as part of Docker for Mac. \033[0m"
echo ''

# Install openemr-cmd
which openemr-cmd &>/dev/null
if [ $? -ne 0 ]
then
	echo -e "\033[30m===>\033[0m \033[32mInstalling openemr-cmd... \033[0m"
    echo ''
	curl -L https://raw.githubusercontent.com/openemr/openemr-devops/master/utilities/openemr-cmd/openemr-cmd > /usr/local/bin/openemr-cmd
	chmod +x /usr/local/bin/openemr-cmd
	echo ''
else
	echo -e "\033[30m===>\033[0m \033[32mOpenEMR-cmd is already installed. \033[0m"
	echo ''
fi

# Get the value after started docker
# Check the installation result
echo '****************************Quick Check****************************'
git --version
docker --version
docker-compose --version
openemr-cmd --version
echo ''
echo -e "\033[36mThe docker status: \033[0m"
echo -e "\033[33mPlease check the docker icon on the top right of the desktop.\033[0m"
echo '********************************************************************'
echo ''

# Startup env
echo '*****************************Startup Env*****************************'
echo -e "\033[34m==>\033[0mRun the below command to startup \033[33measy env\033[0m."
echo -e "\033[32mcd ${CODE_LOCATION}/openemr && openemr-cmd up\033[0m"
echo -e "\033[34m==>\033[0mOr run the below command to startup \033[33minsane env\033[0m."
echo -e "\033[32mcd ${CODE_LOCATION}/openemr/contrib/util/docker && openemr-cmd up\033[0m"
echo '*********************************************************************'
