apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    # Redis High availability with Sentinel on Kubernetes(K8s) configurations
    # -----------------------------------------------------------------------
    
    bind 0.0.0.0
    
    # remove persistence since already supported with support of failover.
    #dbfilename dump.rdb
    #dir /data
    appendonly no
    save ""
    #appendfilename "appendonly.aof"
    
    # Enabled ACL based auth. 
    protected-mode yes
    
    # This is used by the replics nodes to communicate with master to replicate the data.
    # we are using a user called "replication" for this, and the a strong pwd for the same is given in masterauth
    masterauth replicationpassword
    masteruser replication
    
    # this is the second ConfigMap will be mounted to. it has the list of users needed.
    aclfile /conf/acl/users.acl
    
    # tls certs and setting
    tls-cert-file /certs/tls.crt
    tls-key-file /certs/tls.key
    tls-ca-cert-file /certs/ca.crt
    tls-auth-clients no
    # uncomment below (and comment line above) if using redis x509
    # tls-auth-clients yes
    tls-replication yes
    
    # port, each redis nodes will be used (only use tls)
    port 0
    tls-port 6379
    # More configurations are optional, if not provided, redis will consider default values ------
    # ------ More details on configuration : https://redis.io/docs/manual/config/ ------