#!/bin/bash

cat > /root/.my.cnf <<-EOF
[client]
user=root
password=$MYSQL_ROOT_PASSWORD

[mysqladmin]
user=root
password=$MYSQL_ROOT_PASSWORD

[mysqldump]
user=root
password=$MYSQL_ROOT_PASSWORD
EOF

chmod 0600 /root/.my.cnf

echo "/root/.my.cnf deployed"