#!/bin/bash
if [ "$REPLICATION_SLAVE_MASTER_HOST" ]; then
  if [ ! -f /tunnels_id_rsa ]; then
    echo "[ERROR] /tunnels_id_rsa is missing. Replication slave would not be able to connect to master!"
    exit 1
  fi
  
  autossh -M 0 -q -f -N -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3" -o ExitOnForwardFailure=yes -o StrictHostKeyChecking=no -i /tunnels_id_rsa -L 3307:localhost:$REPLICATION_SLAVE_REMOTE_PORT tunnels@$REPLICATION_SLAVE_MASTER_HOST
  # http://linuxaria.com/howto/permanent-ssh-tunnels-with-autossh
  echo "autossh tunnel to $REPLICATION_SLAVE_MASTER_HOST:$REPLICATION_SLAVE_REMOTE_PORT started."
else
  echo "ENV[REPLICATION_SLAVE_MASTER_HOST] is empty. Skipping ssh tunnel creation."
fi