#!/bin/bash

if [ -d /var/lib/mysql/mysql ]; then
  echo "/var/lib/mysql/mysql exists - assuming mysql data dir is populated."

  if [ ! -f /root/.my.cnf ]; then
    create_my_root_cnf
  fi

else
  # If the data folder was created beforehand on the host, it will have different owner. Correct this:
  chown mysql:mysql /var/lib/mysql

  mysql_install_db
  echo "mysql system tables installed"

  mysqld_safe &
  mysqladmin --silent --wait=30 ping || exit 1

  # Delete anonymous users and test table
  mysql -e "DELETE FROM mysql.user WHERE User = '';"
  mysql -e "DROP DATABASE test;"
  echo "Anonymous mysql user account deleted and test db dropped."

  # Secure root account
  mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;"
  mysql -e "UPDATE mysql.user SET Password = PASSWORD('$MYSQL_ROOT_PASSWORD') WHERE User = 'root';"
  mysql -e "FLUSH PRIVILEGES;"
  echo "mysql root password set to ENV[MYSQL_ROOT_PASSWORD]"

  create_my_root_cnf

  # Shutdown the server so that we can start it again so that docker can monitor it
  mysqladmin shutdown
fi

echo "Launching mysqld_safe..."
exec mysqld_safe
