#!/bin/bash
FIRST_ARG=$1

filter_help_output(){
	FILTER_ARG=$1
	LINE_COUNT=$2
	openemr-cmd -h|grep $FILTER_ARG -A $LINE_COUNT
}

if [ $# -eq 0 ]
then
	echo "To search the keyword from openemr-cmd -h output quickly
  Usage: openemr-cmd-h keyword
  e.g.   openemr-cmd-h ssl
  h                         openemr-cmd -h
  docker                    docker-management
  php                       php-management
  test                      test-management
  sweep                     sweep-management
  reset                     reset-management
  backup                    backup-management
  ssl                       ssl-management
  mul                       multisite-management
  api                       api-management
  com                       computational-health-informatics
  webroot                   webroot-management
  others                    others
  keyword                   grep from openemr-cmd -h"
	exit
fi
case "$FIRST_ARG" in
          docker)
		filter_help_output docker-management 8
		;;
	   php)
		filter_help_output php-management 9
		;;
	    test)
		filter_help_output test-management 8
		;;
	    sweep)
		filter_help_output sweep-management 2
		;;
	    reset)
		filter_help_output reset-mamagement 4
		;;
	    backup)
		filter_help_output backup-management 6
		;;
	    ssl)
		filter_help_output ssl-management 18
		;;
	    mul)
		filter_help_output multisite-management 5
		;;
	    api)
		filter_help_output api-management 4
		;;
	    com)
		filter_help_output computational-health-informatics 2
		;;
	    webroot)
		filter_help_output webroot-management 2
		;;
	    others)
		filter_help_output others: 5
		;;
		h)
		openemr-cmd -h
		;;
		*)
		openemr-cmd -h|grep -i $FIRST_ARG
esac
