global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Prometheus
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
         - targets: ['hostIp:3001']

# cAdvisor
  - job_name: 'cadvisor'
    static_configs:
         - targets: ['hostIp:3002']

# alertmanager
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 'hostIp:3003'
# rules
rule_files:
   - "alert-rules.yml"
