global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Prometheus
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
         - targets: ['localhost:9090']

# cAdvisor
  - job_name: 'cadvisor'
    static_configs:
         - targets: ['localhost:8080']

# alertmanager
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 'localhost:9093'
# rules
rule_files:
   - "alert-rules.yml"
