name: Flex 3.16 Docker Build

on:
  workflow_dispatch:

jobs:
  build:
    # Only run from master branch on the main repository
    if: github.repository_owner == 'openemr' && github.repository == 'openemr/openemr-devops' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push flex 3.16 docker
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker/openemr/flex-3.16"
          tags: openemr/openemr:flex-3.16, openemr/openemr:flex
          platforms: linux/amd64,linux/arm64
          push: true
          no-cache: true
