name: Update Docker Hub Description
on:
  push:
    branches:
      - master
    paths:
      - 'docker/openemr/OVERVIEW.md'
jobs:
  dockerhub-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: openemr/openemr
          readme-filepath: ./docker/openemr/OVERVIEW.md
